"""ajout de nouveaux champs

Revision ID: 1473ce8ec9a3
Revises: c5037ed5c1a3
Create Date: 2026-02-26 11:58:20.246523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1473ce8ec9a3'
down_revision = 'c5037ed5c1a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
