"""add audit_logs table

Revision ID: 23cc9f676c70
Revises: bb6cd3e2253a
Create Date: 2026-03-06 06:10:22.989179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23cc9f676c70'
down_revision = 'bb6cd3e2253a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
