"""add payment_confirmed to orders

Revision ID: 24e6d955fe52
Revises: d5f7d4b0284c
Create Date: 2026-03-06 15:09:39.741853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e6d955fe52'
down_revision = 'd5f7d4b0284c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
