"""add seller fields to users

Revision ID: 90859895978f
Revises: 255b927c06be
Create Date: 2026-02-16 15:49:56.143338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90859895978f'
down_revision = '255b927c06be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('seller_approved_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('seller_requested_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('seller_company_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('seller_vat_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('seller_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'seller_address')
    op.drop_column('users', 'seller_vat_number')
    op.drop_column('users', 'seller_company_name')
    op.drop_column('users', 'seller_requested_at')
    op.drop_column('users', 'seller_approved_at')
    # ### end Alembic commands ###
