"""ajout de nouveaux champs

Revision ID: 9a8b9f07461e
Revises: 1473ce8ec9a3
Create Date: 2026-02-26 14:10:12.074672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8b9f07461e'
down_revision = '1473ce8ec9a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
