"""add payment_confirmed to orders

Revision ID: 9f70b198b304
Revises: 9a8b9f07461e
Create Date: 2026-03-04 16:32:49.793631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f70b198b304'
down_revision = '9a8b9f07461e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_confirmed')
    # ### end Alembic commands ###
