"""ajout de la nouvelle table audit

Revision ID: bb6cd3e2253a
Revises: 9f70b198b304
Create Date: 2026-03-06 06:01:44.312551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6cd3e2253a'
down_revision = '9f70b198b304'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
