"""ajout de nouveaux champs

Revision ID: c5037ed5c1a3
Revises: 90859895978f
Create Date: 2026-02-26 11:52:30.689674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5037ed5c1a3'
down_revision = '90859895978f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('accepted_payment_methods', sa.JSON(), nullable=True))
    op.add_column('shops', sa.Column('stripe_account_id', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('stripe_account_status', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('paypal_email', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('paypal_merchant_id', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('moncash_phone', sa.String(), nullable=True))
    op.add_column('shops', sa.Column('moncash_verified', sa.Boolean(), nullable=True))
    op.add_column('shops', sa.Column('natcash_account', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shops', 'natcash_account')
    op.drop_column('shops', 'moncash_verified')
    op.drop_column('shops', 'moncash_phone')
    op.drop_column('shops', 'paypal_merchant_id')
    op.drop_column('shops', 'paypal_email')
    op.drop_column('shops', 'stripe_account_status')
    op.drop_column('shops', 'stripe_account_id')
    op.drop_column('shops', 'accepted_payment_methods')
    # ### end Alembic commands ###
